# III. Tensor Basics in PyTorch

#### Intro to Tensors

##### Understanding Tensors
Tensors form the backbone of any machine learning or deep learning system. They are a mathematical entity that lives in a structure and interacts with other mathematical entities. If you've ever performed calculations with scalars, vectors, or matrices, then you've worked with special cases of tensors.

Tensors are a generalization of scalars, vectors, and matrices to an arbitrary number of dimensions. They are containers for data – almost always numerical data. So, they're a container for numbers. You can think of tensors as multi-dimensional arrays.

##### How are Tensors Different from Vectors and Matrices?
Scalars, vectors, and matrices are all special cases of tensors.

* A scalar is a single number, or you can say it is a 0-dimensional tensor. For example, "7" is a scalar value.

* A vector is an array of numbers, or a 1-dimensional tensor. For example, [1, 2, 3] is a 3-dimensional vector.

* A matrix is a 2-dimensional grid of numbers, or a 2D tensor. For example, [[1, 2, 3], [4, 5, 6], [7, 8, 9]] is a 3x3 matrix.

So, a tensor that contains only one number is a scalar, a tensor with three numbers is a vector, and a tensor with two axes is a matrix. Tensors are defined by three key attributes:

* Number of axes (rank): For instance, a 3D tensor has three axes, and a matrix has two axes.

* Shape: This is a tuple of integers that describes how many dimensions the tensor has along each axis. For example, a matrix's shape might be (3, 5).

* Data type (dtype): This is the type of data contained in the tensor; for example, the tensor's type could be float32, uint8, float64, and so on.

##### Tensors in the Context of Neural Networks
Neural networks take tensors as input, process these tensors using layers (which are also represented as tensors), and output tensors. Here's why tensors are important in the context of neural networks:

* Efficiency and Speed: Tensors are a vital aspect in the field of deep learning algorithms due to the possibility of performing parallel operations on them, which leads to a performance gain. Modern hardware accelerators like GPUs allow tensor operations to be massively parallelized, and frameworks like PyTorch and TensorFlow are designed to efficiently work with tensors on these hardware accelerators, leading to efficient computation even for large-scale neural networks.

* Flexibility: Tensors are highly flexible and can represent a wide range of data. For instance, color images can be represented as 3D tensors. The dimensions correspond to the height, width, and color depth. Even more complex data structures can be represented as tensors. For instance, videos can be represented as 4D tensors, where dimensions correspond to frame index, height, width, and color depth.

* Support for Automatic Differentiation: Deep learning frameworks that use tensors also provide automatic differentiation and gradient calculation, which are invaluable for backpropagation in neural networks. This feature simplifies the implementation of new models and the computation of gradients.

* Scalability and Batch Processing: Tensors enable batch processing of data, which is crucial in training deep learning models. Instead of passing a single data point (scalar) or a single data sample (vector), we can process a batch of data in parallel, leading to greater utilization of the GPU and faster training.

Tensors are fundamental to the operation of neural networks. Their high dimensionality allows for the encapsulation of complex data structures, while their efficient implementation allows for fast computation and suitability for gradient-based optimization algorithms, like those used in training deep learning models.


In [1]:
import torch

#### Creating and manipulating Tensors in PyTorch


In [2]:
# Create a tensor with a single number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
# create a vector with more numbers
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [4]:
# create a matrix
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [5]:
# create a 3-dimensional tensor
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [6]:
# check the shape of tensors
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 3])


#### Tensor Operations and Gradients


In [7]:
# addition
print(t3 + 2)

# multiplication
print(t3 * 2)

# matrix multiplication
print(t3 @ torch.tensor([[2.], [1.]]))

# add 2 tensors
t5 = torch.tensor([[1., 2], [3, 4], [5, 6]])
print(t3 + t5)

# reshape a tensor
print(t3.reshape(1, 6))

tensor([[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[10., 12.],
        [14., 16.],
        [18., 20.]])
tensor([[16.],
        [22.],
        [28.]])
tensor([[ 6.,  8.],
        [10., 12.],
        [14., 16.]])
tensor([[ 5.,  6.,  7.,  8.,  9., 10.]])


#### Tensor Gradients

In [8]:
# create a 3D tensor with gradients enabled
t6 = torch.tensor([
    [[1., 2, 3],
     [3, 4, 5]],
    [[5, 6, 7],
     [7, 8, 9.]]])

w = torch.tensor([[1., 2], [3, 4]], requires_grad=True)
b = torch.tensor([[1.], [2]], requires_grad=True)

# compute the model output
y = w @ t6 + b
print(y)

# compute gradients
y.backward(torch.ones_like(y))
print(w.grad)
print(b.grad)


tensor([[[ 8., 11., 14.],
         [17., 24., 31.]],

        [[20., 23., 26.],
         [45., 52., 59.]]], grad_fn=<AddBackward0>)
tensor([[24., 36.],
        [24., 36.]])
tensor([[6.],
        [6.]])
